# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - doc-test

# Environment variables
env:
  global:
    - GH_REPO_REF: github.com/seznam/httpmockserver.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - cd doc
  - doxygen doxyfile

deploy:
  provider: pages
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_API_KEY
  local_dir: html
  on:
    branch: doc-test
